name: Feature Enhancement
description: Suggest an enhancement to an existing feature for ATProtoKit.
title: "[Feature Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this form! If this is for an issue, please go back and select "Bug Report" or "Documentation Issue."
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Summarize the enchancement in one or two sentences.
  - type: textarea
    id: pain-points
    attributes:
      label: Pain points
      description: Explain in detail what pain points you're trying to solve.
    validations:
      required: true
  - type: textarea
    id: alts
    attributes:
      label: Considered Alternatives
      description: What alternative solutions did you consider and how did they fall short of your expectations?
  - type: dropdown
    id: is-enhancement-breaking-change
    attributes:
      label: Is this a breaking change?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the issue here.
