name: Feature Request
description: Suggest an idea for ATProtoKit.
title: "[Feature Request]: "
labels: ["New Feature"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this form! If this is for an issue, please go back and select "Bug Report" or "Documentation Issue."
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Summarize the feature in one or two sentences.
  - type: textarea
    id: pain-points
    attributes:
      label: Pain points
      description: Explain in detail what pain points you're trying to solve.
    validations:
      required: true
  - type: textarea
    id: alts
    attributes:
      label: Considered Alternatives
      description: What alternative solutions did you consider and how did they fall short of your expectations?
  - type: dropdown
    id: is-feature-breaking-change
    attributes:
      label: Is this a breaking change?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: library-examples
    attributes:
      label: Library Examples
      description: Are there any libraries that have similar features to what you're thinking of? If so, write them down here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the issue here.
