name: Update Documentation on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

#      - name: Archive DocC
#        run: |
#          xcodebuild docbuild -scheme ATProtoKit -destination 'name=My Mac' -derivedDataPath doccarchive
#          DOCC_ARCHIVE="./$(find doccarchive -type d -name 'ATProtoKit.doccarchive')"

#      - name: GH Release
#        uses: softprops/action-gh-release@v2.0.4
#        with:            

    - name: Generate DocC for Web
      run: |
        make docc
        mv docs docc-website

    - name: Move DocC website to docc branch
      run: |
        git fetch --all
        git checkout docc
        git rm -r docs/*
        mkdir -p docs
        mv docc-website/* docs
        rm -r docc-website
        cp CNAME docs/CNAME
        git add docs
        DATE_MSG=$(date "+This website is current as of %b %d, %Y at %H:%M %Z")
        git commit -m "Update DocC website" -m "$DATE_MSG"
        git push origin docc
