# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Swift Package on macOS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - uses: swift-actions/setup-swift@v2
    - name: Get swift version
      run: swift --version # Swift 5.10

    - name: Build
      run: swift build -v

#    - name: Run tests
#      run: swift test -v
