name: Build Swift Package on Ubuntu Linux

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: swift-actions/setup-swift@v2
    - name: Get swift version
      run: swift --version

    - name: Build
      run: swift build -v

#    - name: Run tests
#      run: swift test -v
